"""LLM adapter schemas — typed contracts at the adapter boundary.

These Pydantic models ensure that raw ``ModelResponse`` data from LiteLLM
never leaks past the adapter layer. Every public method returns one of these
types.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class ClassificationResult(BaseModel):
    """Typed classification result from LLM. Never exposes raw ModelResponse."""

    model_config = ConfigDict(extra="ignore")

    action: str
    type: str
    confidence: Literal["high", "low"]
    raw_llm_output: str
    fallback_applied: bool = False


class DraftText(BaseModel):
    """Draft generated by LLM. Branded to distinguish from raw str."""

    content: str
    model_used: str
    fallback_applied: bool = False


class ClassifyOptions(BaseModel):
    """Options for classification calls."""

    allowed_actions: list[str] = Field(min_length=1)
    allowed_types: list[str] = Field(min_length=1)
    temperature: float = Field(default=0.1, ge=0.0, le=1.0)
    max_tokens: int = Field(default=500, gt=0)
    model: str | None = None


class DraftOptions(BaseModel):
    """Options for draft generation calls."""

    temperature: float = Field(default=0.7, ge=0.0, le=1.0)
    max_tokens: int = Field(default=2000, gt=0)
    model: str | None = None


class LLMConfig(BaseModel):
    """Configuration for LLM adapter initialization."""

    classify_model: str
    draft_model: str
    fallback_model: str
    allowed_models: frozenset[str] = Field(default_factory=frozenset)
    api_key: str | None = None
    base_url: str | None = None
    timeout_seconds: int = Field(default=30, gt=0)


class ConnectionTestResult(BaseModel):
    """Result of a non-destructive LLM connectivity check."""

    success: bool
    model_used: str
    latency_ms: int
    error_detail: str | None = None
